services:

  mysql:
    image: mysql:8.0
    volumes: 
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    ports:
      - "8080:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 04042002Mm!
      MYSQL_DATABASE: models_for_pc