version: '3.0'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: model_polosin
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: 123456
    volumes:
      - dbdata:/var/lib/mysql
      - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
    restart: always
  modelpolosinapp:
    depends_on:
      - db
    image: modelpolosin/model_polosin:runtime
    build:
      context: .
    ports:
      - "8080:5000"
volumes:
  dbdata: